# Generated by Django 5.2.17 on 2026-09-17 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontuacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_publico', models.BooleanField(default=False, help_text='Se desativado, o ranking geral não exibirá nomes ou posições públicas.', verbose_name='Exibir Ranking Publicamente')),
                ('top3_publico', models.BooleanField(default=True, help_text='Se desativado, a seção do Top 3 será oculta na página pública.', verbose_name='Exibir Top 3 Publicamente')),
                ('modo_top3', models.CharField(choices=[('NOME_FOTO_PONTOS', 'Nome + Foto + Pontos'), ('NOME_FOTO_SEMPONTOS', 'Nome + Foto sem Pontos'), ('OCULTO_PONTOS', 'Apenas Pontos com Identidade Oculta (🔒)'), ('NOME_PONTOS_SEMFOTO', 'Nome + Pontos sem Foto')], default='NOME_FOTO_PONTOS', help_text='Define quais elementos (nome, foto, pontos) aparecem no Top 3 público.', max_length=30, verbose_name='Modo de Exibição do Top 3')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.AddField(
            model_name='desbravador',
            name='foto',
            field=models.ImageField(blank=True, help_text='Opcional. Foto de perfil do desbravador.', null=True, upload_to='desbravadores/', verbose_name='Foto do Desbravador'),
        ),
        migrations.AddField(
            model_name='desbravador',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Conta associada para que o desbravador possa fazer login e ver seu próprio perfil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desbravador', to=settings.AUTH_USER_MODEL, verbose_name='Conta de Usuário'),
        ),
        migrations.AlterField(
            model_name='desbravador',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desbravadores inativos não aparecem no ranking ou Top 3 públicos.', verbose_name='Ativo'),
        ),
    ]
