# Generated by Django 5.2.17 on 2026-09-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontuacao', '0002_configuracaosistema_desbravador_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='modo_top3',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='ranking_publico',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='top3_publico',
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='mostrar_fotos_ranking',
            field=models.BooleanField(default=False, help_text='Exibe a foto do desbravador no ranking público se disponível.', verbose_name='Mostrar Fotos dos Desbravadores'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='mostrar_nomes_ranking',
            field=models.BooleanField(default=True, help_text='Se desativado, os nomes serão ocultados (Ex: Desbravador 1).', verbose_name='Mostrar Nomes Reais'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='mostrar_pontos_ranking',
            field=models.BooleanField(default=True, help_text='Se desativado, o total de pontos não aparecerá no ranking público.', verbose_name='Mostrar Pontuação Total'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='ranking_limite_publico',
            field=models.IntegerField(default=3, help_text='Ex: 3 para Top 3, 5 para Top 5, 10 para Top 10.', verbose_name='Limite de Posições Públicas (Modo Parcial)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='ranking_modo',
            field=models.CharField(choices=[('COMPLETO', 'Ranking Público Completo'), ('PARCIAL', 'Ranking Parcial (Limitado)'), ('OCULTO', 'Ranking Oculto')], default='PARCIAL', help_text='Completo: exibe todos os membros ativos. Parcial: exibe até o limite configurado. Oculto: não exibe público.', max_length=20, verbose_name='Modo de Exibição do Ranking'),
        ),
        migrations.AlterField(
            model_name='desbravador',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desbravadores inativos não aparecem no ranking público.', verbose_name='Ativo'),
        ),
    ]
